import { ArrayDataSource, DataSource, MapDataSource, ReadOnlyDataSource } from '../stream/data_source.js';
import { DuplexDataSource } from '../stream/duplex_data_source.js';

export type AttributeValue = number | string | boolean | ReadOnlyDataSource<string> | ReadOnlyDataSource<boolean> | ReadOnlyDataSource<number>;
export type ClassType =
    | string
    | ReadOnlyDataSource<string>
    | ReadOnlyDataSource<string[]>
    | Array<string | ReadOnlyDataSource<string>>
    | MapLike<boolean | ReadOnlyDataSource<boolean>>
    | MapDataSource<string, boolean>
    | ArrayDataSource<string>;
export type StyleType = string | ReadOnlyDataSource<string> | Styles | MapDataSource<keyof Styles, string | number>;
/**
 * Type alias for a generic calback taking a parameter and not returning anything
 */
export type Callback<T> = (data?: T) => void;
export type Delegate = () => void;
export type Predicate<T> = (data: T) => boolean;
export type Provider<T> = () => T;
export type Comparator<T1, T2> = (value1: T1, value2: T2) => boolean;
export type Constructor<T> = new (...args: any[]) => T;
export type MapLike<T> = { [key: string]: T };

export type DataDrain<T> = Callback<T> | DataSource<T> | DuplexDataSource<T>;
export declare type ThenArg<T> = T extends PromiseLike<infer U> ? U : T;

export interface Styles {
    accentColor?: string | ReadOnlyDataSource<string>;
    alignContent?: string | ReadOnlyDataSource<string>;
    alignItems?: string | ReadOnlyDataSource<string>;
    alignSelf?: string | ReadOnlyDataSource<string>;
    all?: string | ReadOnlyDataSource<string>;
    animation?: string | ReadOnlyDataSource<string>;
    animationDelay?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    animationDirection?: string | ReadOnlyDataSource<string>;
    animationDuration?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    animationFillMode?: string | ReadOnlyDataSource<string>;
    animationIterationCount?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    animationName?: string | ReadOnlyDataSource<string>;
    animationPlayState?: string | ReadOnlyDataSource<string>;
    animationTimingFunction?: string | ReadOnlyDataSource<string>;
    aspectRatio?: string | ReadOnlyDataSource<string>;

    backdropFilter?: string | ReadOnlyDataSource<string>;
    backfaceVisibility?: string | ReadOnlyDataSource<string>;
    background?: string | ReadOnlyDataSource<string>;
    backgroundAttachment?: string | ReadOnlyDataSource<string>;
    backgroundBlendMode?: string | ReadOnlyDataSource<string>;
    backgroundClip?: string | ReadOnlyDataSource<string>;
    backgroundColor?: string | ReadOnlyDataSource<string>;
    backgroundImage?: string | ReadOnlyDataSource<string>;
    backgroundOrigin?: string | ReadOnlyDataSource<string>;
    backgroundPosition?: string | ReadOnlyDataSource<string>;
    backgroundPositionX?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    backgroundPositionY?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    backgroundRepeat?: string | ReadOnlyDataSource<string>;
    backgroundSize?: string | ReadOnlyDataSource<string>;
    blockSize?: string | ReadOnlyDataSource<string>;
    border?: string | ReadOnlyDataSource<string>;
    borderBlock?: string | ReadOnlyDataSource<string>;
    borderBlockColor?: string | ReadOnlyDataSource<string>;
    borderBlockEnd?: string | ReadOnlyDataSource<string>;
    borderBlockEndColor?: string | ReadOnlyDataSource<string>;
    borderBlockEndStyle?: string | ReadOnlyDataSource<string>;
    borderBlockEndWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderBlockStart?: string | ReadOnlyDataSource<string>;
    borderBlockStartColor?: string | ReadOnlyDataSource<string>;
    borderBlockStartStyle?: string | ReadOnlyDataSource<string>;
    borderBlockStartWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderBlockStyle?: string | ReadOnlyDataSource<string>;
    borderBlockWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderBottom?: string | ReadOnlyDataSource<string>;
    borderBottomColor?: string | ReadOnlyDataSource<string>;
    borderBottomLeftRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderBottomRightRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderBottomStyle?: string | ReadOnlyDataSource<string>;
    borderBottomWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderCollapse?: string | ReadOnlyDataSource<string>;
    borderEndEndRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderEndStartRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderImage?: string | ReadOnlyDataSource<string>;
    borderImageOutset?: string | ReadOnlyDataSource<string>;
    borderImageRepeat?: string | ReadOnlyDataSource<string>;
    borderImageSlice?: string | ReadOnlyDataSource<string>;
    borderImageSource?: string | ReadOnlyDataSource<string>;
    borderImageWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderInline?: string | ReadOnlyDataSource<string>;
    borderInlineColor?: string | ReadOnlyDataSource<string>;
    borderInlineEnd?: string | ReadOnlyDataSource<string>;
    borderInlineEndColor?: string | ReadOnlyDataSource<string>;
    borderInlineEndStyle?: string | ReadOnlyDataSource<string>;
    borderInlineEndWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderInlineStart?: string | ReadOnlyDataSource<string>;
    borderInlineStartColor?: string | ReadOnlyDataSource<string>;
    borderInlineStartStyle?: string | ReadOnlyDataSource<string>;
    borderInlineStartWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderInlineStyle?: string | ReadOnlyDataSource<string>;
    borderInlineWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderLeft?: string | ReadOnlyDataSource<string>;
    borderLeftColor?: string | ReadOnlyDataSource<string>;
    borderLeftStyle?: string | ReadOnlyDataSource<string>;
    borderLeftWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderRight?: string | ReadOnlyDataSource<string>;
    borderRightColor?: string | ReadOnlyDataSource<string>;
    borderRightStyle?: string | ReadOnlyDataSource<string>;
    borderRightWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderSpacing?: string | ReadOnlyDataSource<string>;
    borderStartEndRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderStartStartRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderStyle?: string | ReadOnlyDataSource<string>;
    borderTop?: string | ReadOnlyDataSource<string>;
    borderTopColor?: string | ReadOnlyDataSource<string>;
    borderTopLeftRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderTopRightRadius?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderTopStyle?: string | ReadOnlyDataSource<string>;
    borderTopWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    borderWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    bottom?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    boxDecorationBreak?: string | ReadOnlyDataSource<string>;
    boxReflect?: string | ReadOnlyDataSource<string>;
    boxShadow?: string | ReadOnlyDataSource<string>;
    boxSizing?: string | ReadOnlyDataSource<string>;
    breakAfter?: string | ReadOnlyDataSource<string>;
    breakBefore?: string | ReadOnlyDataSource<string>;
    breakInside?: string | ReadOnlyDataSource<string>;

    captionSide?: string | ReadOnlyDataSource<string>;
    caretColor?: string | ReadOnlyDataSource<string>;
    '@charset'?: string | ReadOnlyDataSource<string>;
    clear?: string | ReadOnlyDataSource<string>;
    clip?: string | ReadOnlyDataSource<string>;
    clipPath?: string | ReadOnlyDataSource<string>;
    color?: string | ReadOnlyDataSource<string>;
    columnCount?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    columnFill?: string | ReadOnlyDataSource<string>;
    columnGap?: string | ReadOnlyDataSource<string>;
    columnRule?: string | ReadOnlyDataSource<string>;
    columnRuleColor?: string | ReadOnlyDataSource<string>;
    columnRuleStyle?: string | ReadOnlyDataSource<string>;
    columnRuleWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    columnSpan?: string | ReadOnlyDataSource<string>;
    columnWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    columns?: string | ReadOnlyDataSource<string>;
    content?: string | ReadOnlyDataSource<string>;
    counterIncrement?: string | ReadOnlyDataSource<string>;
    counterReset?: string | ReadOnlyDataSource<string>;
    counterSet?: string | ReadOnlyDataSource<string>;
    cursor?: string | ReadOnlyDataSource<string>;

    direction?: string | ReadOnlyDataSource<string>;
    display?: string | ReadOnlyDataSource<string>;

    emptyCells?: string | ReadOnlyDataSource<string>;

    filter?: string | ReadOnlyDataSource<string>;
    flex?: string | ReadOnlyDataSource<string>;
    flexBasis?: string | ReadOnlyDataSource<string>;
    flexDirection?: string | ReadOnlyDataSource<string>;
    flexFlow?: string | ReadOnlyDataSource<string>;
    flexGrow?: string | ReadOnlyDataSource<string>;
    flexShrink?: string | ReadOnlyDataSource<string>;
    flexWrap?: string | ReadOnlyDataSource<string>;
    float?: string | ReadOnlyDataSource<string>;
    font?: string | ReadOnlyDataSource<string>;
    '@fontFace'?: string | ReadOnlyDataSource<string>;
    fontFamily?: string | ReadOnlyDataSource<string>;
    fontFeatureSettings?: string | ReadOnlyDataSource<string>;
    fontKerning?: string | ReadOnlyDataSource<string>;
    fontLanguageOverride?: string | ReadOnlyDataSource<string>;
    fontSize?: string | ReadOnlyDataSource<string> | number | ReadOnlyDataSource<number>;
    fontSizeAdjust?: string | ReadOnlyDataSource<string>;
    fontStretch?: string | ReadOnlyDataSource<string>;
    fontStyle?: string | ReadOnlyDataSource<string>;
    fontSynthesis?: string | ReadOnlyDataSource<string>;
    fontVariant?: string | ReadOnlyDataSource<string>;
    fontVariantAlternates?: string | ReadOnlyDataSource<string>;
    fontVariantCaps?: string | ReadOnlyDataSource<string>;
    fontVariantEastAsian?: string | ReadOnlyDataSource<string>;
    fontVariantLigatures?: string | ReadOnlyDataSource<string>;
    fontVariantNumeric?: string | ReadOnlyDataSource<string>;
    fontVariantPosition?: string | ReadOnlyDataSource<string>;
    fontWeight?: string | ReadOnlyDataSource<string> | number | ReadOnlyDataSource<number>;

    gap?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    grid?: string | ReadOnlyDataSource<string>;
    gridArea?: string | ReadOnlyDataSource<string>;
    gridAutoColumns?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridAutoFlow?: string | ReadOnlyDataSource<string>;
    gridAutoRows?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridColumn?: string | ReadOnlyDataSource<string>;
    gridColumnEnd?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridColumnGap?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridColumnStart?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridGap?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridRow?: string | ReadOnlyDataSource<string>;
    gridRowEnd?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridRowGap?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridRowStart?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    gridTemplate?: string | ReadOnlyDataSource<string>;
    gridTemplateAreas?: string | ReadOnlyDataSource<string>;
    gridTemplateColumns?: string | ReadOnlyDataSource<string>;

    hangingPunctuation?: string | ReadOnlyDataSource<string>;
    height?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    hyphens?: string | ReadOnlyDataSource<string>;
    hypenateCharacter?: string | ReadOnlyDataSource<string>;

    imageRendering?: string | ReadOnlyDataSource<string>;
    inlineSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    inset?: string | ReadOnlyDataSource<string>;
    insetBlock?: string | ReadOnlyDataSource<string>;
    insetBlockEnd?: string | ReadOnlyDataSource<string>;
    insetBlockStart?: string | ReadOnlyDataSource<string>;
    insetInline?: string | ReadOnlyDataSource<string>;
    insetInlineEnd?: string | ReadOnlyDataSource<string>;
    insetInlineStart?: string | ReadOnlyDataSource<string>;
    isolation?: string | ReadOnlyDataSource<string>;

    justifyContent?: string | ReadOnlyDataSource<string>;
    justifyItems?: string | ReadOnlyDataSource<string>;
    justifySelf?: string | ReadOnlyDataSource<string>;

    left?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    letterSpacing?: string | ReadOnlyDataSource<string>;
    lineBreak?: string | ReadOnlyDataSource<string>;
    lineHeight?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    listStyle?: string | ReadOnlyDataSource<string>;
    listStyleImage?: string | ReadOnlyDataSource<string>;
    listStylePosition?: string | ReadOnlyDataSource<string>;
    listStyleType?: string | ReadOnlyDataSource<string>;

    margin?: string | ReadOnlyDataSource<string>;
    marginBlock?: string | ReadOnlyDataSource<string>;
    marginBlockEnd?: string | ReadOnlyDataSource<string>;
    marginBlockStart?: string | ReadOnlyDataSource<string>;
    marginBottom?: string | ReadOnlyDataSource<string>;
    marginInline?: string | ReadOnlyDataSource<string>;
    marginInlineEnd?: string | ReadOnlyDataSource<string>;
    marginInlineStart?: string | ReadOnlyDataSource<string>;
    marginLeft?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    marginRight?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    marginTop?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    mask?: string | ReadOnlyDataSource<string>;
    maskClip?: string | ReadOnlyDataSource<string>;
    maskComposite?: string | ReadOnlyDataSource<string>;
    maskImage?: string | ReadOnlyDataSource<string>;
    maskMode?: string | ReadOnlyDataSource<string>;
    maskOrigin?: string | ReadOnlyDataSource<string>;
    maskPosition?: string | ReadOnlyDataSource<string>;
    maskRepeat?: string | ReadOnlyDataSource<string>;
    maskSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    maskType?: string | ReadOnlyDataSource<string>;
    maxHeight?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    maxWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    maxBlockSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    maxInlineSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    minBlockSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    minInlineSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    minHeight?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    minWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    mixBlendMode?: string | ReadOnlyDataSource<string>;

    objectFit?: string | ReadOnlyDataSource<string>;
    objectPosition?: string | ReadOnlyDataSource<string>;
    offset?: string | ReadOnlyDataSource<string>;
    offsetAnchor?: string | ReadOnlyDataSource<string>;
    offsetDistance?: string | ReadOnlyDataSource<string>;
    offsetPath?: string | ReadOnlyDataSource<string>;
    offsetRotate?: string | ReadOnlyDataSource<string>;
    opacity?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    order?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    orphans?: string | ReadOnlyDataSource<string>;
    outline?: string | ReadOnlyDataSource<string>;
    outlineColor?: string | ReadOnlyDataSource<string>;
    outlineOffset?: string | ReadOnlyDataSource<string>;
    outlineStyle?: string | ReadOnlyDataSource<string>;
    outlineWidth?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    overflow?: string | ReadOnlyDataSource<string>;
    overflowAnchor?: string | ReadOnlyDataSource<string>;
    overflowWrap?: string | ReadOnlyDataSource<string>;
    overflowX?: string | ReadOnlyDataSource<string>;
    overflowY?: string | ReadOnlyDataSource<string>;
    overscrollBehavior?: string | ReadOnlyDataSource<string>;
    overscrollBehaviorBlock?: string | ReadOnlyDataSource<string>;
    overscrollBehaviorInline?: string | ReadOnlyDataSource<string>;
    overscrollBehaviorX?: string | ReadOnlyDataSource<string>;
    overscrollBehaviorY?: string | ReadOnlyDataSource<string>;

    padding?: string | ReadOnlyDataSource<string>;
    paddingBlock?: string | ReadOnlyDataSource<string>;
    paddingBlockEnd?: string | ReadOnlyDataSource<string>;
    paddingBlockStart?: string | ReadOnlyDataSource<string>;
    paddingBottom?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    paddingInline?: string | ReadOnlyDataSource<string>;
    paddingInlineEnd?: string | ReadOnlyDataSource<string>;
    paddingInlineStart?: string | ReadOnlyDataSource<string>;
    paddingLeft?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    paddingRight?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    paddingTop?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    pageBreakAfter?: string | ReadOnlyDataSource<string>;
    pageBreakBefore?: string | ReadOnlyDataSource<string>;
    pageBreakInside?: string | ReadOnlyDataSource<string>;
    paintOrder?: string | ReadOnlyDataSource<string>;
    perspective?: string | ReadOnlyDataSource<string>;
    perspectiveOrigin?: string | ReadOnlyDataSource<string>;
    placeContent?: string | ReadOnlyDataSource<string>;
    placeItems?: string | ReadOnlyDataSource<string>;
    placeSelf?: string | ReadOnlyDataSource<string>;
    pointerEvents?: string | ReadOnlyDataSource<string>;
    position?: string | ReadOnlyDataSource<string>;

    quotes?: string | ReadOnlyDataSource<string>;

    resize?: string | ReadOnlyDataSource<string>;
    right?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    rotate?: string | ReadOnlyDataSource<string>;
    rowGap?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;

    scale?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    scrollBehavior?: string | ReadOnlyDataSource<string>;
    scrollMargin?: string | ReadOnlyDataSource<string>;
    scrollMarginBlock?: string | ReadOnlyDataSource<string>;
    scrollMarginBlockEnd?: string | ReadOnlyDataSource<string>;
    scrollMarginBlockStart?: string | ReadOnlyDataSource<string>;
    scrollMarginBottom?: string | ReadOnlyDataSource<string>;
    scrollMarginInline?: string | ReadOnlyDataSource<string>;
    scrollMarginInlineEnd?: string | ReadOnlyDataSource<string>;
    scrollMarginInlineStart?: string | ReadOnlyDataSource<string>;
    scrollMarginLeft?: string | ReadOnlyDataSource<string>;
    scrollMarginRight?: string | ReadOnlyDataSource<string>;
    scrollMarginTop?: string | ReadOnlyDataSource<string>;
    scrollPadding?: string | ReadOnlyDataSource<string>;
    scrollPaddingBlock?: string | ReadOnlyDataSource<string>;
    scrollPaddingBlockEnd?: string | ReadOnlyDataSource<string>;
    scrollPaddingBlockStart?: string | ReadOnlyDataSource<string>;
    scrollPaddingBottom?: string | ReadOnlyDataSource<string>;
    scrollPaddingInline?: string | ReadOnlyDataSource<string>;
    scrollPaddingInlineEnd?: string | ReadOnlyDataSource<string>;
    scrollPaddingInlineStart?: string | ReadOnlyDataSource<string>;
    scrollPaddingLeft?: string | ReadOnlyDataSource<string>;
    scrollPaddingRight?: string | ReadOnlyDataSource<string>;
    scrollPaddingTop?: string | ReadOnlyDataSource<string>;
    scrollSnapALign?: string | ReadOnlyDataSource<string>;
    scrollSnapStop?: string | ReadOnlyDataSource<string>;
    scrollSnapType?: string | ReadOnlyDataSource<string>;
    scrollbarColor?: string | ReadOnlyDataSource<string>;

    tabSize?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    tableLayout?: string | ReadOnlyDataSource<string>;
    textAlign?: string | ReadOnlyDataSource<string>;
    textAlignLast?: string | ReadOnlyDataSource<string>;
    textCombineUpright?: string | ReadOnlyDataSource<string>;
    textDecoration?: string | ReadOnlyDataSource<string>;
    textDecorationColor?: string | ReadOnlyDataSource<string>;
    textDecorationLine?: string | ReadOnlyDataSource<string>;
    textDecorationStyle?: string | ReadOnlyDataSource<string>;
    textDecorationThickness?: string | ReadOnlyDataSource<string>;
    textEmphasis?: string | ReadOnlyDataSource<string>;
    textEmphasisColor?: string | ReadOnlyDataSource<string>;
    textEmphasisPosition?: string | ReadOnlyDataSource<string>;
    textEmphasisStyle?: string | ReadOnlyDataSource<string>;
    textIndent?: string | ReadOnlyDataSource<string>;
    textJustify?: string | ReadOnlyDataSource<string>;
    textOrientation?: string | ReadOnlyDataSource<string>;
    textOverflow?: string | ReadOnlyDataSource<string>;
    textShadow?: string | ReadOnlyDataSource<string>;
    textTransform?: string | ReadOnlyDataSource<string>;
    textUnderlineOffset?: string | ReadOnlyDataSource<string>;
    textUnderlinePosition?: string | ReadOnlyDataSource<string>;
    top?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    transform?: string | ReadOnlyDataSource<string>;
    transformOrigin?: string | ReadOnlyDataSource<string>;
    transformStyle?: string | ReadOnlyDataSource<string>;
    transition?: string | ReadOnlyDataSource<string>;
    transitionDelay?: string | ReadOnlyDataSource<string>;
    transitionDuration?: string | ReadOnlyDataSource<string>;
    transitionProperty?: string | ReadOnlyDataSource<string>;
    transitionTimingFunction?: string | ReadOnlyDataSource<string>;
    translate?: string | ReadOnlyDataSource<string>;

    unicodeBidi?: string | ReadOnlyDataSource<string>;
    userSelect?: string | ReadOnlyDataSource<string>;

    verticalAlign?: string | ReadOnlyDataSource<string>;
    visibility?: string | ReadOnlyDataSource<string>;

    whiteSpace?: string | ReadOnlyDataSource<string>;
    widows?: string | ReadOnlyDataSource<string>;
    width?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
    wordBreak?: string | ReadOnlyDataSource<string>;
    wordSpacing?: string | ReadOnlyDataSource<string>;
    wordWrap?: string | ReadOnlyDataSource<string>;
    writingMode?: string | ReadOnlyDataSource<string>;

    zIndex?: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;

    [key: string]: string | number | ReadOnlyDataSource<string> | ReadOnlyDataSource<number>;
}
