import { AProps } from './nodes/a';
import { AreaProps } from './nodes/area';
import { AudioProps } from './nodes/audio';
import { BrProps } from './nodes/br';
import { ButtonProps } from './nodes/button';
import { CanvasProps } from './nodes/canvas';
import { DataProps } from './nodes/data';
import { DetailsProps } from './nodes/details';
import { DivProps } from './nodes/div';
import { FormProps } from './nodes/form';
import { HeadingProps } from './nodes/heading';
import { IFrameProps } from './nodes/iframe';
import { ImgProps } from './nodes/img';
import { InputProps } from './nodes/input';
import { LabelProps } from './nodes/label';
import { LiProps } from './nodes/li';
import { LinkProps } from './nodes/link';
import { OlProps } from './nodes/ol';
import { OptionProps } from './nodes/option';
import { PProps } from './nodes/p';
import { PreProps } from './nodes/pre';
import { ProgressProps } from './nodes/progress';
import { QProps } from './nodes/q';
import { ScriptProps } from './nodes/script';
import { SelectProps } from './nodes/select';
import { SourceProps } from './nodes/source';
import { SpanProps } from './nodes/span';
import { SvgProps } from './nodes/svg';
import { TableProps } from './nodes/table';
import { TdProps } from './nodes/td';
import { TextAreaProps } from './nodes/textarea';
import { ThProps } from './nodes/th';
import { TimeProps } from './nodes/time';
import { TitleProps } from './nodes/title';
import { TrProps } from './nodes/tr';
import { UlProps } from './nodes/ul';
import { VideoProps } from './nodes/video';
import { StyleProps } from './nodes/style';
import { BodyProps } from './nodes/body';
import { HeadProps } from './nodes/head';
import { TemplateProps } from './nodes/template';
import { AurumElementProps } from './nodes/special/aurum_element';

export * from './stream/data_source';
export * from './stream/object_data_source';

export * from './utilities/aurum';
export * from './utilities/cancellation_token';

export * from './nodes/special/custom';
export * from './nodes/special/router';
export * from './nodes/special/suspense';
export * from './nodes/special/switch';

export * from './nodes/special/aurum_element';

declare global {
	namespace JSX {
		interface IntrinsicElements {
			button: ButtonProps;
			div: DivProps;
			input: InputProps;
			li: LiProps;
			span: SpanProps;
			style: StyleProps;
			ul: UlProps;
			p: PProps;
			img: ImgProps;
			link: LinkProps;
			canvas: CanvasProps;
			a: AProps;
			article: AurumElementProps;
			br: BrProps;
			form: FormProps;
			label: LabelProps;
			ol: OlProps;
			pre: PreProps;
			progress: ProgressProps;
			table: TableProps;
			td: TdProps;
			tr: TrProps;
			th: ThProps;
			textarea: TextAreaProps;
			h1: AurumElementProps;
			h2: AurumElementProps;
			h3: AurumElementProps;
			h4: AurumElementProps;
			h5: AurumElementProps;
			h6: AurumElementProps;
			header: AurumElementProps;
			footer: AurumElementProps;
			nav: AurumElementProps;
			b: AurumElementProps;
			i: AurumElementProps;
			script: ScriptProps;
			abbr: AurumElementProps;
			area: AreaProps;
			aside: AurumElementProps;
			audio: AudioProps;
			em: AurumElementProps;
			heading: HeadingProps;
			iframe: IFrameProps;
			noscript: AurumElementProps;
			option: OptionProps;
			q: QProps;
			select: SelectProps;
			source: SourceProps;
			title: TitleProps;
			video: VideoProps;
			tbody: AurumElementProps;
			tfoot: AurumElementProps;
			thead: AurumElementProps;
			summary: AurumElementProps;
			details: DetailsProps;
			sub: AurumElementProps;
			sup: AurumElementProps;
			svg: SvgProps;
			data: DataProps;
			time: TimeProps;
			body: BodyProps;
			head: HeadProps;
			template: TemplateProps;
		}
	}
}
